In [8]:
import os
import json
import pandas as pd 
import traceback

In [9]:
  import os
  from dotenv import load_dotenv, find_dotenv

In [10]:
from langchain_openai import ChatOpenAI

In [11]:
import os
from dotenv import load_dotenv, find_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI

load_dotenv(find_dotenv())

llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash",
    google_api_key=os.getenv("GOOGLE_API_KEY"),
    temperature=0.3,
)

In [12]:
%pip install -U langchain langchain-openai langchain-core langchain-community pypdf python-dotenv

Requirement already satisfied: langchain in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (1.4.6)
Requirement already satisfied: langchain-openai in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (1.7.2)
Requirement already satisfied: langchain-core in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (1.6.11)
Requirement already satisfied: langchain-community in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (0.4.2)
Requirement already satisfied: pypdf in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (6.20.1)
Requirement already satisfied: python-dotenv in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (1.2.4)
Requirement already satisfied: langgraph<1.3.0,>=1.2.12 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain) (1.2.15)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain) (2.14.1)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core) (1.35)
Requirement already satisfied: langchain-protocol>=0.0.17 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.14.9 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core) (0.14.9)
Requirement already satisfied: packaging>=23.2.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core) (26.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core) (0.17.1)
Requirement already satisfied: anyio in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (4.15.1)
Requirement already satisfied: certifi in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (1.0.9)
Requirement already satisfied: idna in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (3.20)
Requirement already satisfied: h11>=0.16 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core) (0.16.0)
Requirement already satisfied: jsonpointer>=3.2 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.2.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.3.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langgraph<1.3.0,>=1.2.12->langchain) (4.3.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langgraph<1.3.0,>=1.2.12->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.6 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langgraph<1.3.0,>=1.2.12->langchain) (0.4.7)
Requirement already satisfied: xxhash>=3.5.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langgraph<1.3.0,>=1.2.12->langchain) (4.0.1)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langgraph-checkpoint<5.0.0,>=4.3.0->langgraph<1.3.0,>=1.2.12->langchain) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langgraph-sdk<0.5.0,>=0.4.6->langgraph<1.3.0,>=1.2.12->langchain) (3.13.0)
Requirement already satisfied: websockets<17,>=14 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langgraph-sdk<0.5.0,>=0.4.6->langgraph<1.3.0,>=1.2.12->langchain) (16.1.1)
Requirement already satisfied: distro>=1.7.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core) (2.13.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core) (1.3.1)
Requirement already satisfied: zstandard>=0.23.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core) (0.25.0)
Requirement already satisfied: httpcore2==2.13.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.14.9->langchain-core) (2.13.1)
Requirement already satisfied: truststore>=0.10 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.14.9->langchain-core) (0.10.5)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: openai<4.0.0,>=2.45.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-openai) (3.31.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-openai) (0.14.0)
Requirement already satisfied: jiter<1,>=0.16.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (0.17.0)
Requirement already satisfied: regex in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2026.9.29)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-community) (3.14.5)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-community) (1.0.8)
Requirement already satisfied: numpy>=1.26.2 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-community) (2.5.4)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-community) (2.16.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-community) (2.1.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.25.1)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.14.9->langchain-core) (3.5.2)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.14.9->langchain-core) (2.8.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_community.callbacks import get_openai_callback
from pypdf import PdfReader

C:\Users\GICHUKI THUITA\AppData\Local\Temp\ipykernel_22476\3670598187.py:5: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.callbacks import get_openai_callback

In [14]:
import json

RESPONSE_JSON = {
    "1": {
        "mcq": "multiple choice question",
        "options": {
            "a": "choice here",
            "b": "choice here",
            "c": "choice here",
            "d": "choice here",
        },
        "correct": "correct answer",
    },
    "2": {
        "mcq": "multiple choice question",
        "options": {
            "a": "choice here",
            "b": "choice here",
            "c": "choice here",
            "d": "choice here",
        },
        "correct": "correct answer",
    },
    "3": {
        "mcq": "multiple choice question",
        "options": {
            "a": "choice here",
            "b": "choice here",
            "c": "choice here",
            "d": "choice here",
        },
        "correct": "correct answer",
    },
}

In [15]:
TEMPLATE = """
Text:{text}
You are an expert MCQ maker. Given the above text, it is your job to \
create a quiz of {number} multiple choice questions for {subject} students in {tone} tone.
Make sure the questions are not repeated and check all the questions to be conforming to the text as well.
Make sure to format your response like RESPONSE_JSON below and use it as a guide. \
Ensure to make {number} MCQs.
### RESPONSE_JSON
{response_json}
"""

In [16]:
from langchain_core.prompts import PromptTemplate

quiz_generation_prompt = PromptTemplate(
    input_variables=["text", "number", "subject", "tone", "response_json"],
    template=TEMPLATE,
)

In [17]:
from langchain_core.output_parsers import StrOutputParser

quiz_chain = quiz_generation_prompt | llm | StrOutputParser()

In [18]:
TEMPLATE2 = """
You are an expert English grammarian and writer. Given a Multiple Choice Quiz for {subject} students.\
You need to evaluate the complexity of the question and give a complete analysis of the quiz. Only use at max 50 words for complexity analysis.
If the quiz is not at par with the cognitive and analytical abilities of the students,\
update the quiz questions which need to be changed and change the tone such that it perfectly fits the student abilities.
Quiz_MCQs:
{quiz}

Check from an expert English Writer of the above quiz:
"""

In [19]:
from langchain_core.prompts import PromptTemplate

quiz_evaluation_prompt = PromptTemplate(
    input_variables=["subject", "quiz"],
    template=TEMPLATE2,
)

In [20]:
from langchain_core.output_parsers import StrOutputParser

review_chain = quiz_evaluation_prompt | llm | StrOutputParser()

In [21]:
from langchain_core.runnables import RunnablePassthrough

generate_evaluate_chain = (
    RunnablePassthrough.assign(quiz=quiz_chain)
    | RunnablePassthrough.assign(review=review_chain)
)

In [22]:
from langchain_core.runnables import RunnablePassthrough

generate_evaluate_chain = (
    RunnablePassthrough.assign(quiz=quiz_chain)
    | RunnablePassthrough.assign(review=review_chain)
)

In [23]:
from langchain_core.globals import set_verbose

set_verbose(True)

In [24]:
%pip install -U langchain-google-genai

Requirement already satisfied: langchain-google-genai in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (4.4.2)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-google-genai) (1.2.0)
Requirement already satisfied: google-genai<3.0.0,>=2.20.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-google-genai) (2.31.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.6.10 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-google-genai) (1.6.11)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-google-genai) (2.14.1)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-genai<3.0.0,>=2.20.0->langchain-google-genai) (4.15.1)
Requirement already satisfied: google-auth<3.0.0,>=2.56.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (2.62.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-genai<3.0.0,>=2.20.0->langchain-google-genai) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-genai<3.0.0,>=2.20.0->langchain-google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-genai<3.0.0,>=2.20.0->langchain-google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-genai<3.0.0,>=2.20.0->langchain-google-genai) (16.1.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-genai<3.0.0,>=2.20.0->langchain-google-genai) (4.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-genai<3.0.0,>=2.20.0->langchain-google-genai) (1.9.0)
Requirement already satisfied: sniffio in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-genai<3.0.0,>=2.20.0->langchain-google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (3.20)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (50.0.2)
Requirement already satisfied: certifi in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (1.35)
Requirement already satisfied: langchain-protocol>=0.0.17 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.14.9 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (0.14.9)
Requirement already satisfied: packaging>=23.2.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (26.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (6.0.3)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (0.17.1)
Requirement already satisfied: jsonpointer>=3.2 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (3.2.1)
Requirement already satisfied: httpx2<3,>=2 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (2.13.1)
Requirement already satisfied: orjson>=3.9.14 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (3.13.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from langsmith<1.0.0,>=0.14.9->langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (0.25.0)
Requirement already satisfied: httpcore2==2.13.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.14.9->langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (2.13.1)
Requirement already satisfied: truststore>=0.10 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.14.9->langchain-core<2.0.0,>=1.6.10->langchain-google-genai) (0.10.5)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->langchain-google-genai) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (3.5.2)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (2.8.0)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (2.1.1)
Requirement already satisfied: pycparser in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (3.11)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\Users\GICHUKI THUITA\mcqgen\env\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

In [25]:
import os
from dotenv import load_dotenv, find_dotenv
from google import genai

load_dotenv(find_dotenv(), override=True)
client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))

for m in client.models.list():
    if "generateContent" in (m.supported_actions or []):
        print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.1-flash-lite-image
models/gemini-nano-banana-2.1
models/gemini-3.5-flash
models/gemini-3.5-flash-lite
models/gemini-omni-flash-preview
models/gemini-omni-1.1-flash
models/gemini-3.5-transcribe
models/gemini-3.6-flash
models/gemini-3.7-flash
models/gemini-3.8-flash
models/gemini-4-argon
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/lyria-3.5
models/gemini-3.1-flash-tts-preview
models/gemini-3.8-flash-tts
models/gemini-3.8-flash-lite-tts
models/gemini-robotics-er-2-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/antigravity-preview-09-2026
models/antigravity-preview-latest
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025

In [26]:
import os
from dotenv import load_dotenv, find_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI

load_dotenv(find_dotenv(), override=True)

candidates = [
    "gemini-flash-latest",
    "gemini-flash-lite-latest",
    "gemini-2.5-flash-lite",
    "gemini-2.5-flash",
    "gemini-3-flash-preview",
    "gemini-3.1-flash-lite",
]

working = None
for name in candidates:
    try:
        test = ChatGoogleGenerativeAI(
            model=name,
            google_api_key=os.getenv("GOOGLE_API_KEY"),
            temperature=0.3,
        )
        reply = test.invoke("Say hello in one short sentence.").content
        print(f"WORKS  {name}: {reply}")
        working = working or name
    except Exception as e:
        print(f"FAILS  {name}: {str(e)[:150]}")

print("\nUse this model:", working)

FAILS  gemini-flash-latest: Error calling model 'gemini-flash-latest' (RESOURCE_EXHAUSTED): 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current
WORKS  gemini-flash-lite-latest: [{'type': 'text', 'text': 'Hello, how can I help you today?', 'extras': {'signature': 'EmAKXgFpFH0TmkXb8C/fXCayb1HQ3ZAPSB5t6LP2zIg6fIdNepzubnDwD3aV6D620WNwOnGzNMOdB22JkhNhdCzKXy4LiUvhBpx9eoEAPQVywqZXDgYIbYhBD9W7cCyq0Lc='}}]
FAILS  gemini-2.5-flash-lite: Error calling model 'gemini-2.5-flash-lite' (NOT_FOUND): 404 NOT_FOUND. {'error': {'code': 404, 'message': 'This model models/gemini-2.5-flash-lite is
FAILS  gemini-2.5-flash: Error calling model 'gemini-2.5-flash' (NOT_FOUND): 404 NOT_FOUND. {'error': {'code': 404, 'message': 'This model models/gemini-2.5-flash is no longer
WORKS  gemini-3-flash-preview: [{'type': 'text', 'text': 'Hello, how can I help you today?', 'extras': {'signature': 'EpwHCpkHAWkUfRP9IDOC35Bp0+7UCzKKC7j+l68EuGtElMiaDzNNcGpBERWzlGhCsOpHQWhtJb/HPg+SwYmcqifgdWZKlLr+9Tkduck5qW5k7pAXYldlkIJ8NtTmAWI397jyJEy0qArCalubglwC4OsNsmeoc5wU/OChshSzcTA03JNQ5DvDieplCOy2iGgMUS1VO4ADGD8k6Gg9fWVYMuJZ9wfQMfU2WBkC/Pllz2zvMjXetYX7ENXH8t66Ov8YeXP7J/XIQi7OLh8JlXJqDK8AFHDTDl0TMID2ydquZ6p8EQeoi8rKTmiMhH+SM0Z63b4Hj8mmXP4/oceH7lZMFMnpihHFOkXriaH+n3Va0i00naeJg/e3v9Vem/YoL4B2CVSKCjzgeQx2J7pkUYmKHa3kvubb4VbaHumKdPynh7Y9BAd+u60bw84OjA4Dd267K9mb1Mb22+Se3xQS84aHZQZq9gIdKVrzPtc2fm2cPSJW9U+XtYhnsQX/rsGINQCES1+jYNWWUG+0v2Pl4uhvHMPn0U0T4ppsZEDeQBf0G4azeySzWHAJANtseRUDjOLvBWCemE3UOHODb7ChOS1C1hb2muHBEB9AEJDvdufVyNrGE7SKh5yjbFM+LrVRNfEMPO/drq6Bpmtaivfw9G8J3juwNkk+MXqHNetH85cOjdu48Y/7SlIUvrgHAozbPNgtAD4sa9Wj4Dg0kVnMHxtVzsOkilybfE21IF96orE4N6MJdeHkAfUbxR6flJnuPUTP2dNn8lirUVWD+r+3sWwF3i/pxv7YHfROjqjWjaANRzlXvtxocGys1k4yOr3zaeGjZd7WopjsP0qMgt+v9zxp2MmduwWzOKERk5802lzvWp0VsYGgl74C5hPZ8Zx6zj9IUqBGaLRwMBEK6C3K3M2B62t6ALx9Ri5CWL6ByV+OQYhkr+QlxVexsdJL27WLOLitxFCWMQVKgGaFBHGNRIjPXm3BC+kiouZjG5+DFt3S0ujdtlFF2ityqlrDhH32W12TVMX6dvr6iPAuW/O97MNaNx9y7SDtEXl3SxGQgnjlRYjOgrPeKOHU/Cb9pFRrb6ZdQpNMw1QOp9a5RHv3itt1RX0tKjCVK1nSrd+DainZJrYoN2ybvhW/8ZB5oUyH1QGYr9DTDJXnrgafdl/WRCZZN66bOwLzpj85l2aqoPcH9JcauSNqguHzMr8ad/Ap8Ult76oxfQ7aixdsEcz4lu3i'}}]
WORKS  gemini-3.1-flash-lite: [{'type': 'text', 'text': 'Hello, it is nice to meet you!', 'extras': {'signature': 'EnMKcQFpFH0T2t6elmQrdGOIW++qt4AJ4CX61t85od6x/sFmKKdq/B3lFZxhoHLubPrrEf6tqymOmUH8Cpxk3dJtJTpvJqycRtuNA7RHAo+o8aTTCA2iWnU9xvO1eBjBYUWSfnpVNlpmWQkG/uCWDFo3uxfG'}}]

Use this model: gemini-flash-lite-latest

In [27]:
import os
import json
import re
from dotenv import load_dotenv, find_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

load_dotenv(find_dotenv(), override=True)

llm = ChatGoogleGenerativeAI(
    model="gemini-flash-lite-latest",
    google_api_key=os.getenv("GOOGLE_API_KEY"),
    temperature=0.3,
    max_retries=5,
)
print(llm.invoke("Say hello in one short sentence.").text)

Hello, how can I help you today?

In [28]:
RESPONSE_JSON = {
    "1": {
        "mcq": "multiple choice question",
        "options": {"a": "choice here", "b": "choice here", "c": "choice here", "d": "choice here"},
        "correct": "correct answer",
    },
    "2": {
        "mcq": "multiple choice question",
        "options": {"a": "choice here", "b": "choice here", "c": "choice here", "d": "choice here"},
        "correct": "correct answer",
    },
    "3": {
        "mcq": "multiple choice question",
        "options": {"a": "choice here", "b": "choice here", "c": "choice here", "d": "choice here"},
        "correct": "correct answer",
    },
}

In [29]:
TEMPLATE = """
Text:{text}
You are an expert MCQ maker. Given the above text, it is your job to \
create a quiz of {number} multiple choice questions for {subject} students in {tone} tone.
Make sure the questions are not repeated and check all the questions to be conforming to the text as well.
Make sure to format your response like RESPONSE_JSON below and use it as a guide. \
Ensure to make {number} MCQs.
Return ONLY valid JSON with no extra text.
### RESPONSE_JSON
{response_json}
"""

TEMPLATE2 = """
You are an expert English grammarian and writer. Given a Multiple Choice Quiz for {subject} students.\
You need to evaluate the complexity of the question and give a complete analysis of the quiz. Only use at max 50 words for complexity analysis.
If the quiz is not at par with the cognitive and analytical abilities of the students,\
update the quiz questions which need to be changed and change the tone such that it perfectly fits the student abilities.
Quiz_MCQs:
{quiz}

Check from an expert English Writer of the above quiz:
"""

quiz_generation_prompt = PromptTemplate(
    input_variables=["text", "number", "subject", "tone", "response_json"],
    template=TEMPLATE,
)

quiz_evaluation_prompt = PromptTemplate(
    input_variables=["subject", "quiz"],
    template=TEMPLATE2,
)

In [30]:
quiz_chain = quiz_generation_prompt | llm | StrOutputParser()
review_chain = quiz_evaluation_prompt | llm | StrOutputParser()

generate_evaluate_chain = (
    RunnablePassthrough.assign(quiz=quiz_chain)
    | RunnablePassthrough.assign(review=review_chain)
)

In [31]:
TEXT = """Artificial Intelligence (AI) is a branch of computer science that aims to create software or machines that exhibit human-like intelligence. This can include learning from experience, understanding natural language, and solving problems."""

result = generate_evaluate_chain.invoke({
    "text": TEXT,
    "number": 5,
    "subject": "pretrained transformer",
    "tone": "simple",
    "response_json": json.dumps(RESPONSE_JSON),
})

print(result["quiz"])
print("\n--- REVIEW ---\n")
print(result["review"])

{
  "1": {
    "mcq": "What is Artificial Intelligence (AI) a branch of?",
    "options": {
      "a": "Computer science",
      "b": "Mechanical engineering",
      "c": "Biology",
      "d": "Mathematics"
    },
    "correct": "a"
  },
  "2": {
    "mcq": "What is the main goal of AI?",
    "options": {
      "a": "To build faster computer processors",
      "b": "To create software or machines that exhibit human-like intelligence",
      "c": "To replace all human jobs",
      "d": "To design video games"
    },
    "correct": "b"
  },
  "3": {
    "mcq": "Which of the following is included as a capability of AI in the text?",
    "options": {
      "a": "Flying airplanes",
      "b": "Cooking food",
      "c": "Learning from experience",
      "d": "Creating physical energy"
    },
    "correct": "c"
  },
  "4": {
    "mcq": "According to the text, what kind of language can AI understand?",
    "options": {
      "a": "Programming language only",
      "b": "Natural language",
      "c": "Ancient language",
      "d": "Machine code"
    },
    "correct": "b"
  },
  "5": {
    "mcq": "Besides learning and understanding language, what else can AI do?",
    "options": {
      "a": "Solving problems",
      "b": "Traveling the world",
      "c": "Creating art",
      "d": "Building hardware"
    },
    "correct": "a"
  }
}

--- REVIEW ---

### Complexity Analysis
The original quiz is far too simplistic, relying on basic recall rather than evaluating the advanced cognitive, analytical, and contextual processing abilities expected of pretrained transformer students. It lacks linguistic nuance and technical depth.

***

### Updated Quiz (Tailored for Pretrained Transformer Students)

```json
{
  "1": {
    "mcq": "Within the broader scope of computer science, how is Artificial Intelligence epistemologically situated regarding cognitive simulation?",
    "options": {
      "a": "As an auxiliary hardware optimization protocol",
      "b": "As a foundational discipline dedicated to synthesizing cognitive faculties algorithmically",
      "c": "As a subset of deterministic database management",
      "d": "As a peripheral methodology for mechanical automation"
    },
    "correct": "b"
  },
  "2": {
    "mcq": "Which teleological objective best encapsulates the primary paradigm of artificial general intelligence research?",
    "options": {
      "a": "Maximizing floating-point operations per second",
      "b": "Replicating heuristic reasoning and adaptive autonomy mirroring human cognition",
      "c": "Optimizing legacy procedural programming paradigms",
      "d": "Standardizing graphical rendering pipelines"
    },
    "correct": "b"
  },
  "3": {
    "mcq": "In the context of machine epistemology, which attribute distinguishes advanced AI systems from static rule-based programs?",
    "options": {
      "a": "The capacity for inductive inference and experiential generalization",
      "b": "Pre-programmed execution of finite state machines",
      "c": "Rigid adherence to hard-coded decision trees",
      "d": "Exclusively executing vectorized mathematical transformations"
    },
    "correct": "a"
  },
  "4": {
    "mcq": "How do modern transformer architectures primarily parse unstructured linguistic inputs?",
    "options": {
      "a": "By converting syntax directly into binary machine code",
      "b": "By contextualizing natural language via semantic vector spaces and attention mechanisms",
      "c": "By parsing strictly formatted context-free grammars",
      "d": "By translating lexical tokens into archaic dialects"
    },
    "correct": "b"
  },
  "5": {
    "mcq": "Beyond pattern recognition and semantic parsing, what core computational competency underpins high-level AI synthesis?",
    "options": {
      "a": "Multi-variable problem-solving and probabilistic optimization",
      "b": "Physical fabrication of semiconductor substrates",
      "c": "Kinetic locomotion across variable terrains",
      "d": "Thermodynamic energy harvesting"
    },
    "correct": "a"
  }
}
```

In [32]:
%pip install -q pandas

Note: you may need to restart the kernel to use updated packages.

In [33]:
import pandas as pd

def clean_json(text):
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    return text

quiz_dict = json.loads(clean_json(result["quiz"]))

rows = []
for number, q in quiz_dict.items():
    options = " | ".join(f"{k}: {v}" for k, v in q["options"].items())
    rows.append({"No": number, "MCQ": q["mcq"], "Choices": options, "Correct": q["correct"]})

quiz_table = pd.DataFrame(rows)
quiz_table

,No,MCQ,Choices,Correct
0,1,What is Artificial Intelligence (AI) a branch of?,a: Computer science | b: Mechanical engineerin...,a
1,2,What is the main goal of AI?,a: To build faster computer processors | b: To...,b
2,3,Which of the following is included as a capabi...,a: Flying airplanes | b: Cooking food | c: Lea...,c
3,4,"According to the text, what kind of language c...",a: Programming language only | b: Natural lang...,b
4,5,"Besides learning and understanding language, w...",a: Solving problems | b: Traveling the world |...,a

In [34]:
quiz_table.to_csv("quiz.csv", index=False)

In [35]:
from pypdf import PdfReader

def read_file(path):
    if path.lower().endswith(".pdf"):
        reader = PdfReader(path)
        return "\n".join(page.extract_text() or "" for page in reader.pages)
    elif path.lower().endswith(".txt"):
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    else:
        raise ValueError("Unsupported file type. Use a .pdf or .txt file.")

In [36]:
file_path = "data.txt"
TEXT = read_file(file_path)

print("Characters read:", len(TEXT))
print(TEXT[:500])

Characters read: 6123
HOW A TRANSFORMER WORKS IN AN AI SETUP
Study Notes for AI Engineering and Generative AI
1. Introduction
In Artificial Intelligence, a Transformer is a neural network architecture that helps AI systems learn relationships between pieces of data, especially words and other tokens in a sequence. Transformers power many modern Large Language Models (LLMs), including GPT-style models. They are used in chatbots, AI agents, document analysis, code assistants, translation and many other applications.
2.

In [37]:
print(TEXT)

HOW A TRANSFORMER WORKS IN AN AI SETUP
Study Notes for AI Engineering and Generative AI
1. Introduction
In Artificial Intelligence, a Transformer is a neural network architecture that helps AI systems learn relationships between pieces of data, especially words and other tokens in a sequence. Transformers power many modern Large Language Models (LLMs), including GPT-style models. They are used in chatbots, AI agents, document analysis, code assistants, translation and many other applications.
2. The Basic Idea
Consider the sentence: “The electrician repaired the circuit because it was faulty.” To interpret the word “it”, a model needs to relate it to other words in the sentence. A Transformer uses a mechanism called self-attention to learn which parts of the input are relevant to one another.
Input text: The sentence or other data supplied to the model.
Tokenization: Split the input into tokens such as words, word parts or punctuation.
Embeddings and positional information: Represent tokens numerically and encode their positions or order.
Transformer layers: Apply self-attention and feed-forward neural networks to build context-aware representations.
Output probabilities: In a GPT-style model, estimate which token is likely to come next.
3. The Five Main Stages Inside a Transformer
Stage 1: Tokenization
The input is split into tokens. A token may be a whole word, part of a word, punctuation mark or another text unit.
Stage 2: Embeddings and positional information
Each token is represented by a numerical vector. Position information helps the model distinguish word order. For example, “the trainee teaches the trainer” and “the trainer teaches the trainee” have different meanings.
Stage 3: Self-attention
Each token uses information from relevant tokens to build a context-aware representation. Attention weights determine how strongly information from other tokens contributes.
Stage 4: Feed-forward networks and repeated layers
The model transforms attention results through neural network layers. Many Transformer designs use residual connections and normalization to support stable training.
Stage 5: Output generation
In a GPT-style language model, the final representation is used to calculate probabilities for the next token. A decoding strategy selects a token, and the process repeats to generate a response.
4. Understanding Query, Key and Value (Q, K, V)
Self-attention creates three learned representations from each token: Query (Q), Key (K) and Value (V).
Query (Q): Represents what information a token is looking for.
Key (K): Represents features used to determine how relevant a token is to a query.
Value (V): Contains the information that is combined and passed forward according to attention weights.
A useful analogy is a library: the query is your search question, the key is a book’s description, and the value is the useful content of the selected book.
The standard scaled dot-product attention equation is:
Attention(Q, K, V) = softmax((QKᵀ) / √dₖ) V
Here, dₖ is the dimension of the key vectors. Scaling by its square root helps control the magnitude of the scores before softmax converts them into attention weights.
5. What Is Multi-Head Attention?
Multi-head attention calculates several attention patterns in parallel. Their outputs are combined so the model can represent different kinds of relationships. For example, in an electrical training document, attention may learn useful relationships among equipment names, technical terms and references. These are possible learned patterns, not fixed jobs assigned to individual heads.
6. What Does a Transformer Look Like in an AI System?
A Transformer is the neural network architecture, not the entire AI application. A deployed AI system often includes a user interface, application logic, optional retrieval or tools, the model itself, and response handling.
User interface: Chatbot, website, mobile application or AI agent.
Application layer: Builds prompts, applies business rules, retrieves relevant information and may call tools.
Transformer-based model: Processes tokens through attention and other neural network layers.
Output handling: Returns generated text, structured output or a tool-call request to the application.
7. Example: An AI Assistant for Electrical Training
An AI assistant could answer trainee questions about conduit installation, wiring diagrams and assessment criteria. A typical workflow is:
1.A trainee submits a question.
2.If retrieval is configured, the application finds relevant training notes.
3.The application sends the question and relevant context to a Transformer-based language model.
4.The model generates a response.
5.The application displays the response and may validate or format it.
The Transformer generates the response. The retrieval system, application logic and user interface provide additional capabilities; they are not themselves the Transformer.
8. Main Types of Transformer Architectures
Architecture	How it works	Typical applications
Encoder-only	Builds contextual representations of input.	Text classification, embeddings
Decoder-only	Predicts subsequent tokens using preceding context.	Chatbots, code generation, GPT-style LLMs
Encoder-decoder	Encodes an input and generates an output from it.	Translation, summarization
These are broad architectural categories. Modern models may use additional techniques beyond these basic designs.
9. How to Begin Experimenting as an AI Engineer
Beginner: Use a pretrained Transformer through an API.
Intermediate: Load a pretrained model with PyTorch and Hugging Face Transformers.
Advanced: Study attention tensors, implement a small Transformer, and experiment with training or fine-tuning.
10. Recommended Learning Order
Learn these concepts in sequence: tokenization, embeddings, Query/Key/Value, self-attention, multi-head attention, feed-forward layers, and next-token prediction. This sequence provides a practical foundation for understanding GPT-style models.
Further Reading
Vaswani, A. et al. (2017). “Attention Is All You Need.” arXiv:1706.03762.
https://arxiv.org/abs/1706.03762

In [38]:
from langchain_core.callbacks import get_usage_metadata_callback

In [39]:
TEXT = read_file("data.txt")
NUMBER = 5
SUBJECT = "Electrical Installation"   # change to your subject
TONE = "simple"

print("Characters read:", len(TEXT))

Characters read: 6123

In [40]:
with get_usage_metadata_callback() as cb:
    response = generate_evaluate_chain.invoke({
        "text": TEXT,
        "number": NUMBER,
        "subject": SUBJECT,
        "tone": TONE,
        "response_json": json.dumps(RESPONSE_JSON),
    })

print(response["quiz"])
print("\n--- REVIEW ---\n")
print(response["review"])
print("\n--- TOKENS ---")
print(cb.usage_metadata)

{
  "1": {
    "mcq": "In the sentence 'The electrician repaired the circuit because it was faulty,' what mechanism does a Transformer use to understand what 'it' refers to?",
    "options": {
      "a": "Tokenization",
      "b": "Self-attention",
      "c": "Positional encoding",
      "d": "Feed-forward networking"
    },
    "correct": "b"
  },
  "2": {
    "mcq": "During which stage of a Transformer is the input text split into smaller units like whole words, word parts, or punctuation marks?",
    "options": {
      "a": "Tokenization",
      "b": "Self-attention",
      "c": "Output generation",
      "d": "Embedding"
    },
    "correct": "a"
  },
  "3": {
    "mcq": "In the library analogy used for Query, Key, and Value (Q, K, V), what does the Query represent?",
    "options": {
      "a": "The useful content of the selected book",
      "b": "A book's description",
      "c": "Your search question",
      "d": "The library building"
    },
    "correct": "c"
  },
  "4": {
    "mcq": "Which type of Transformer architecture is typically used for GPT-style models, chatbots, and code generation?",
    "options": {
      "a": "Encoder-only",
      "b": "Decoder-only",
      "c": "Encoder-decoder",
      "d": "Retrieval-only"
    },
    "correct": "b"
  },
  "5": {
    "mcq": "In an AI system designed to help electrical trainees, what is the role of the Transformer-based model?",
    "options": {
      "a": "Provide the user interface and buttons",
      "b": "Retrieve notes from the database",
      "c": "Generate the response by processing tokens through attention layers",
      "d": "Format the final output for the mobile application"
    },
    "correct": "c"
  }
}

--- REVIEW ---

### Complexity Analysis
The original quiz is fundamentally misaligned with Electrical Installation students. Instead of testing electrical concepts, it assesses Natural Language Processing and AI Transformer architectures. The phrasing is overly academic and irrelevant to trade students, lacking appropriate domain-specific context.

***

### Updated Quiz (Tailored for Electrical Installation Students)

{
  "1": {
    "mcq": "When installing a branch circuit in a commercial building, which factor is primarily used to determine the correct minimum wire gauge (AWG) size?",
    "options": {
      "a": "The color of the insulation",
      "b": "The ampacity rating and allowable voltage drop",
      "c": "The brand of the conduit",
      "d": "The height of the ceiling"
    },
    "correct": "b"
  },
  "2": {
    "mcq": "During the rough-in stage of residential wiring, what is the primary purpose of installing electrical boxes securely to the wall studs?",
    "options": {
      "a": "To provide structural support for device termination and prevent movement",
      "b": "To improve the acoustic insulation of the room",
      "c": "To ensure proper grounding of non-metallic sheathed cable",
      "d": "To reduce the overall resistance of the circuit"
    },
    "correct": "a"
  },
  "3": {
    "mcq": "In troubleshooting a faulty 120V branch circuit where the breaker keeps tripping under load, what does a persistent short circuit typically represent?",
    "options": {
      "a": "A high-resistance ground connection",
      "b": "An unintended, direct path between the ungrounded (hot) conductor and a grounded or grounding conductor",
      "c": "A standard operating condition for inductive loads",
      "d": "An open switch in the circuit path"
    },
    "correct": "b"
  },
  "4": {
    "mcq": "Which type of Overcurrent Protective Device (OCPD) is typically required by the NEC for all 15-amp and 20-amp circuits in residential dwelling unit kitchens and bathrooms?",
    "options": {
      "a": "Standard thermal-magnetic circuit breaker",
      "b": "Arc-Fault Circuit Interrupter (AFCI)",
      "c": "Ground-Fault Circuit Interrupter (GFCI)",
      "d": "Time-delay fuse"
    },
    "correct": "c"
  },
  "5": {
    "mcq": "When utilizing a digital multimeter to verify that a three-phase motor circuit has been safely de-energized, what is the correct testing procedure?",
    "options": {
      "a": "Test line-to-line and line-to-ground on all phases, then verify the meter on a known live source",
      "b": "Check only the phase A conductor visually without testing",
      "c": "Measure the resistance of the motor windings while the system is live",
      "d": "Measure the ambient temperature of the control panel"
    },
    "correct": "a"
  }
}

--- TOKENS ---
{'gemini-3.5-flash-lite': {'total_tokens': 3361, 'output_tokens': 1213, 'input_tokens': 2148, 'input_token_details': {'cache_read': 0}}}

In [43]:
def find_quiz(data):
    """Dig through the response until we find the {"1": {"mcq":..., "options":..., "correct":...}} structure."""
    # LangChain message object
    if hasattr(data, "content"):
        data = data.content

    # List of content blocks, e.g. [{"type": "text", "text": "..."}]
    if isinstance(data, list):
        data = "".join(b.get("text", "") if isinstance(b, dict) else str(b) for b in data)

    # JSON text, possibly wrapped in ```json fences
    if isinstance(data, str):
        cleaned = re.sub(r"^```(?:json)?|```$", "", data.strip(), flags=re.MULTILINE).strip()
        data = json.loads(cleaned)

    if isinstance(data, dict):
        # Found it: values are question dicts
        first = next(iter(data.values()), None)
        if isinstance(first, dict) and "mcq" in first:
            return data
        # Otherwise it's a wrapper: search inside each value
        for v in data.values():
            try:
                return find_quiz(v)
            except Exception:
                continue

    raise ValueError("Could not find quiz questions in response")


quiz = find_quiz(response)

quiz_table_data = []
for key, value in quiz.items():
    mcq = value["mcq"]
    options = " | ".join(f"{k}: {v}" for k, v in value["options"].items())
    correct = value["correct"]
    quiz_table_data.append({"MCQ": mcq, "Choices": options, "Correct": correct})

quiz_df = pd.DataFrame(quiz_table_data)
quiz_df.to_csv("machinelearning.csv", index=False)

quiz_df

,MCQ,Choices,Correct
0,multiple choice question,a: choice here | b: choice here | c: choice he...,correct answer
1,multiple choice question,a: choice here | b: choice here | c: choice he...,correct answer
2,multiple choice question,a: choice here | b: choice here | c: choice he...,correct answer

In [44]:
def parse_quiz(data):
    # Message object or list of content blocks -> plain text
    if hasattr(data, "content"):
        data = data.content
    if isinstance(data, list):
        data = "".join(b.get("text", "") if isinstance(b, dict) else str(b) for b in data)

    # Text -> dict (take everything from the first { to the last })
    if isinstance(data, str):
        start, end = data.find("{"), data.rfind("}")
        data = json.loads(data[start:end + 1])
    return data


# Use the "quiz" key from the chain output, not "response_json" (that's just the template)
raw_quiz = response["quiz"] if isinstance(response, dict) and "quiz" in response else response
quiz = parse_quiz(raw_quiz)

quiz_table_data = []
for key, value in quiz.items():
    mcq = value["mcq"]
    options = " | ".join(f"{k}: {v}" for k, v in value["options"].items())
    correct = value["correct"]
    quiz_table_data.append({"MCQ": mcq, "Choices": options, "Correct": correct})

quiz_df = pd.DataFrame(quiz_table_data)
quiz_df.to_csv("machinelearning.csv", index=False)

quiz_df

,MCQ,Choices,Correct
0,In the sentence 'The electrician repaired the ...,a: Tokenization | b: Self-attention | c: Posit...,b
1,During which stage of a Transformer is the inp...,a: Tokenization | b: Self-attention | c: Outpu...,a
2,"In the library analogy used for Query, Key, an...",a: The useful content of the selected book | b...,c
3,Which type of Transformer architecture is typi...,a: Encoder-only | b: Decoder-only | c: Encoder...,b
4,In an AI system designed to help electrical tr...,a: Provide the user interface and buttons | b:...,c

In [1]:
   import sys, os
   sys.path.append(os.path.abspath(".."))

   from src.mcqgenerator.logger import logging

   logging.info("Starting MCQ generation")

In [2]:
import sys, os
sys.path.append(os.path.abspath(".."))

from src.mcqgenerator.logger import logging

logging.info("Starting MCQ generation")
print("Logger works")

Logger works

In [3]:
from datetime import datetime

datetime.now().strftime('%m_%d_%Y_%H_%M_%S')

'10_16_2026_11_20_33'